### ISSUE TITLE
Handeling backend authentication

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#180]
I would love some advice:
I have my own backend but use Ionic for my user management and authentication.
1) I need to protect my backend routes so only someone who is authenticated can use it.
2) I need need to protect my backend routes so users(session?) can only access there own data.
3) I need to be able to revoke a user - As it stands once a user is logged in, there is no way to log him out, even deleting the user won't help. 

Should I validate the user every time he opens the app?  Sounds to me like if 1 and 2 are implemented, I can just use a 403 to manually log him out.

Would appreciate some best practice advice on how to integrate this with my system. Preferably I would like to avoid a secondary authentication mechanism but i'm not sure how.

**Comment by ericb** [comment]
Hey @sagivf 👋 

So there's a few different things to touch on here so i'll try to touch on each of them separately.

> Should I validate the user every time he opens the app?

In your case, yes, absolutely. There are a number of different reasons to do so and there is a few different approaches to handling it based on how sensitive the app data is. Perhaps the most practical example of this is to keep the user logged into the app (so they are not burdened with a login every time) but to verify that the user is still valid by making a request for the User's data. If they are offline it's really up to you to decide whether or not it should log them out (sensitive data perhaps?) or allow them to continue being logged in until such a time you can verify they still should be authenticated.

> I need to protect my backend routes so only someone who is authenticated can use it.

Ultimately the best way to do this is to implement your own authentication/session system in your backend and then use our custom authentication to handle the login, but you can then manage the user's state from your own session management - in other words, calls would be made to your server using your own auth scheme instead of ours. 

Having said that, it sounds like perhaps you're looking for a way to use our authentication in your own backend. This is something we haven't tackled from an ease-of-use standpoint, but you could in fact send our auth user token to your backend, which can make a call to our API to lookup the user and verify the user/app data is as you expect it. However, this will add an external call to each of your routes which might not be ok for your use case.

> I need need to protect my backend routes so users(session?) can only access there own data.

This is really tied to the answer above.

> I need to be able to revoke a user - As it stands once a user is logged in, there is no way to log him out, even deleting the user won't help.

With your own user system or ours? If you remove the user from the app in our auth system, the user's token will become invalidated and they will no longer be able to make requests against their own data/app. This will not ping the device so any user currently logged in will remain logged in until they are logged out but they will not be able to make any authenticated calls to our services.

Hope that helps!
Cheers 🍻

**Comment by sagivf** [comment]
Hey @ericb thanks for the details response.
Authenticating against your backend would be great but an extra api call on each route/request would indeed be to costly.

Setting up my own authentication is something I wanted to avoid at the moment. I think it's also a problem with the invalidation scenario, it would mean I need to invalidate on both systems.

What would be best is If I could use ionics generated jwt and only validate it against my system.
If i'm not mistaken all I would need is the `token secret` - correct? Perhaps you could add an option to set the secret via ionic.io? Maybe even supply some sort of node module (that would be great for other user/cloud services as well)?
There are probably some implications i'm not thinking of, but this is I suppose a common use case so I thinks it's worth investigating...

By the way - do you have any advice on invalidating tokens? can you disclose how you guys are doing it - a blacklist of tokens?

**Comment by ericb** [comment]
I don't think we've previously thought of doing a shared secret for the auth service. I'll keep that in mind and see what some of the rest of the team thinks. At first thought, it seems like it would be really useful, but I'm unsure of a demand overall. 

As for invalidating tokens, they are currently revoked when you delete the user, but I believe we've been meaning to add a way for you to revoke tokens individually.

**Comment by sagivf** [comment]
Awesome, let me know if there are any conclusions! Thanks 😄
