### ISSUE TITLE
Angular 1/Ionic 1 Feedback

### ISSUE THREAD

**Issue by dwieeb** [driftyco/ionic-cloud#3]
I'm asking for feedback on the Angular 1/Ionic 1 support in the Ionic Cloud client, particularly the new config setup. Using this library is recommended for Ionic 1 projects, and will be the future of what once was the `ionic-platform-web-client`. For usage, see [the readme](https://github.com/driftyco/ionic-cloud) for now. Also see the [Migration Guide](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide) to see how to port existing `ionic-platform-web-client` code to the new cloud client.

1. What did you like?
1. What did you dislike/what could be improved?
1. Anything else?

**Comment by Maistho** [comment]
Converted my app to use the angular bindings, and all seems to be well.

Previously there was an `api_key` field in the config, which seems to have been removed. Does my app no longer need an API key in order to access Ionic Cloud?

:+1: Config works better when inside angular as a provider. 
:+1: Pretty much the same interface with or without angular bindings
:+1: `Ionic Cloud` is a better name than `ionic-platform-web-client`
:+1: Fewer bugs than before! :tada:

:-1: No migration guide from `ionic-platform-web-client` to `Ionic Cloud`
:-1: Manually copying is bad, I will have to apply upgrades manually as well. I'm not sure if gulp is used by all Ionic 1 projects as default, but if that's the case maybe 
:-1: unclear as to what the `.io-config.json` file does anymore.
:-1: Cannot set config using `ionic config` any longer, so either fix that or remove `ionic config` completely?
:-1: Ionic Framework uses bower by default, and this project does not. I'm all for not using bower, but it should be consistent.

**Comment by dwieeb** [comment]
`api_key` was specifically for the alpha API, which is deprecated and being removed very soon (next Friday). It is no longer needed for our beta API, as most API calls use mobile user tokens through auth.

- The migration guide is coming! I am finalizing a few things.
- Manual copying is bad, yes. Installs and updates will need to do this. Unfortunately the alternative is to automatically do this for people, which people didn't like either. There's not really a good solution to this. Gulp isn't as much of a necessity in Ionic 1 apps as Ionic 2. For those that do use it, we can provide a snippet for a task that copies the file for them, but at that point isn't it just easier to reference the docs for the `cp` command? 😖 
- `.io-config.json` is part of the legacy config system. As part of the migration guide that's coming, we are recommending people just delete it.
- `ionic config` is being removed soon in the Ionic CLI, I believe. There are many things happening all at once at Ionic, and it's going to be difficult to sync up everything. It may be a volatile development environment for a few weeks or months, but from then on out it should be smooth sailing 😄 
- At Ionic we much prefer npm over bower, but the bower integration with the CLI is something we can't decouple immediately. 

Thanks so much, @Maistho! Hope I addressed your concerns. I'm glad you enjoyed the improvements.

**Comment by Maistho** [comment]
Thanks for the response!

I think my CLI is recreating `.io-config.json` when I run certain commands. Guess I'll open an issue at the CLI for that :smiley:

Regarding the manual copying, I get the problem. I wouldn't want it to happen automatically either, since we use a custom build anyway.
I guess the best option is to inform the user that they will need to either update it manually whenever a new version is released or setup a build system similar to gulp.

I'm happy to see development happening on this project. Ionic Cloud is very useful and the better tools makes it a lot better!

**Comment by dwieeb** [comment]
@Maistho Well, the CLI team isn't _ready_ for that, yet. That's the problem. We're still trying to support other users who are not using your exact workflow. Like I said, it'll be a little rocky for people for a short while and then everything should be a lot better. 👍 

Yes, we will be documenting the installing and updating of this library for Ionic 1 projects, for sure!

I'm happy to put some development time into it. It was sorely needed.

**Comment by dwieeb** [comment]
Hey all. I decided to publicize my [Migration Guide](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide). Things may change as we go forward with the beta, so it's sort of a "living" migration guide. Fortunately, Github wikis are version controlled so you can see the changes I make in this repo corresponding to the new revisions in the Migration Guide.

**Comment by genox** [comment]
What about providing dist files via bower?

**Comment by Chrisp1tv** [comment]
Hi all :) Sorry if I'm not posting in the good topic, but I hope I am. After migrate from `ionic-platform-web-client` to `ionic-cloud`, I can't get Push notifications working in browser... I was using development mode (`dev_push = true`) whit `ionic-platform-web-client`, but I think push notifications aren't working anymore in browser with `ionic-cloud` ?

And, one more question. How to define the push plugin options like it was possible before ? I have to say the documentation is really poor at the moment and some important points are missing, like this one. :)

**Comment by ericb** [comment]
@Chrisp1tv Development pushes were removed in the cloud client. We will be implementing true browser push support with a later release.

As for documentation, we are still working on the full documentation for the new cloud client. The current guides are just very basic things to get someone going, but are not intended to guide you through full usage yet.

**Comment by dwieeb** [comment]
The Cloud Client should be pretty stable at the moment. I have a few tasks for me next week to do some finishing touches and then we should be good to go. Thanks for the feedback everyone!

**Comment by Mr-Anonymous** [comment]
Its interesting. If I was to use Ionic Cloud in Ionic 1 / Angular 1.5, then shouldn't that break things since Ionic Cloud uses Angular 2? Is it possible to use ionic cloud services in Ionic 1 app that uses Angular 1.5? Or should the whole app needs to be upgraded to Angular 2 / Ionic 2? When I read the instructions, it shows the configuration needs to be added to the `src/app/app.module.ts` file which doesn't apply in ionic 1. Can we add the same in the `run block` of Angular 1 and still upgrade to Ionic Cloud instead of `ionic-platform-web-client`? So can someone enlighten me here please?
