### ISSUE TITLE
Use Angular 1 Promises

### ISSUE THREAD

**Issue by dwieeb** [driftyco/ionic-cloud#4]
Using angular 1 promises would aid in compatibility of the angular 1 integration. Wrapping the `$ionicSomething` factories in angular 1 promises would provide features such as the finally function and integration with angular change detection. This issue is to investigate how to do that.

Possibly use [`when`](https://docs.angularjs.org/api/ng/service/$q#when)?

Thanks @astik for the original issue: https://github.com/driftyco/ionic-platform-web-client/issues/110

**Comment by meticoeus** [comment]
One option for angular 1 projects would be to use the bluebird promise library. It exposes its scheduler which can then be tied to angular's digest cycle effciently. 

The [angular-bluebird-promises](https://github.com/mattlewis92/angular-bluebird-promises) library takes care of the integration and replaces the $q service implementation with the bluebird implementation for you.

**Comment by Maistho** [comment]
@meticoeus what is the advantage of using bluebird over the builtin $q?

Currently I wrap my promises with `$q.all([promise])`, but I'm not sure why... Will test with `$q.when(promise)` instead, since that seems to be the preferred way to do it.

**Comment by dwieeb** [comment]
I guess bluebird adds more features? We don't need the additional features and I'd rather not have another dependency included in our bundle. We should be able to make use of `$q` to wrap our promises.

**Comment by meticoeus** [comment]
An option for a user of the library is to replace the global Promise from es6-promises (or native implementation) with bluebird promises. All uses of Promise in this and other libraries and your app code will be using a single implementation that can now inter-op with the digest cycle. You can then use the API directly instead of the wrapped versions, which may make sense in project that is being migrated. Just import the module in the normal way

**Comment by dwieeb** [comment]
Oh, I see! That native implementation replacement and digest cycle hook-in is something I've been wondering about. An option would be to document how to set up that library in Ionic 1 projects. We can't depend on it because our client must work for angular 1, Angular 2, and non-angular projects.

I personally think wrapping the promises with angular's `$q` would be better because it's an api that angular devs are familiar with. It just seems more consistent.

**Comment by meticoeus** [comment]
The `$q` wrapper approach is probably the best way to go to keep things simple and familiar for ng1 devs.

Documenting that you can and how setup bluebird so that you can avoid the wrapper might be useful for anyone doing a 1->2 migration so they can use the library directly without the ng1 modules.

**Comment by meticoeus** [comment]
For reference to anyone considering this strategy, there was already a [discussion](https://github.com/angular/angular.js/issues/6697) about making bluebird usable in angular 2 before they dropped $q for native promises.

The main take away is that $q is silent about uncaught promise rejections while bluebird is not. Some ng1 libraries like ui-router are guilty of this so your console will blow up until you change bluebird's configuration. Of course, that feature is useful when reviewing your own code.

**Comment by dwieeb** [comment]
@meticoeus @Maistho Got this working! If `window.Promise` is undefined, set it to `$q`, otherwise patch our use of promises with `$q.when`. 🎉
