### ISSUE TITLE
Debugging a bad APN certificate

### ISSUE THREAD

**Issue by florentsuc** [driftyco/ionic-cloud#90]
I spent quite some time debugging a bad APN certificate. It's totally an error from my side, but I think the `/push/notifications` endpoint should show a different state & status. Or I'm missing something.

Steps to reproduce:

- Upload an APN certificate to Ionic.io
- Revoke it from the apple developer console.
- Run the app on your iOS device. You should be able to register & get a token.
- Try to send a notification to this token, nothing will be received. However, the notification is shown as enqueued & locked (state / status)

If you try these steps again without revoking the certificate, it will work.

So I think we should be able to debug a revoked/invalid APN certificate more easily.

What do you think about it?

**Comment by ericb** [comment]
@florentsuc Because the notification can hold more than just APNS messages, the errors are tied directly to the messages that are attempting to send. We mention in the [docs](http://docs.ionic.io/services/push/#checking-notification-status) that you can look at the message status, but if you use the dashboard, you should be able to see a notification status breakdown that will update as messages are sent out.
